<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>VHS • Account access</title>
<style>
:root{font-family:system-ui,sans-serif;color:#223831;background:#f2f6f3}*{box-sizing:border-box}body{margin:0;padding:36px 20px}main{max-width:960px;margin:auto}header{margin-bottom:28px}h1{font-size:32px;margin:8px 0}h2{font-size:21px;margin-top:0}p{line-height:1.6}small,.muted{color:#5b6e66}.badge{font-size:12px;font-weight:700;letter-spacing:2px;color:#28764f}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.card{background:white;border:1px solid #dce6df;border-radius:16px;padding:24px;margin-bottom:20px;box-shadow:0 4px 12px #264b3210}label{display:block;font-size:13px;font-weight:600;margin:14px 0 5px}input,select{width:100%;padding:11px;border:1px solid #b9ccc0;border-radius:7px;font:inherit}input[type=checkbox]{width:auto}button{background:#23744f;color:white;border:0;border-radius:7px;padding:12px 18px;font:inherit;cursor:pointer;margin-top:16px}button.secondary{background:#e8f1eb;color:#204c34}button:disabled{opacity:.6;cursor:wait}.row{display:flex;gap:12px}.row>*{flex:1}#message{position:sticky;top:12px;z-index:2;padding:14px;border-radius:10px;background:#e2f0e6;border:1px solid #9ebea7;white-space:pre-wrap;margin-bottom:20px}#message.error{background:#fff0ed;border-color:#d7aaa0}#message:empty{display:none}a{color:#216842}.full{grid-column:1/-1}[hidden]{display:none!important}@media(max-width:720px){.grid{grid-template-columns:1fr}.row{display:block}body{padding:20px 12px}}
</style><script src="/auth-client.js" defer></script></head>
<body><main><header><span class="badge">VHS ANIMAL WELLNESS CENTER</span><h1>Account access</h1><p class="muted">Register, verify your account, and sign in. Keep this browser open while entering your verification code.</p></header>
<div id="message" role="status" aria-live="polite"></div>
<div class="card" id="account" hidden><h2>Signed in</h2><p id="identity"></p><button id="logout">Log out</button><p class="muted">Account authentication is connected to Laravel. Pet, appointment, and clinical portal integration is the next migration stage.</p></div>
<div class="grid">
<section class="card"><h2>Create an owner account</h2><form id="register">
<div class="row"><div><label>First name<input name="first_name" required maxlength="50" autocomplete="given-name"></label></div><div><label>Last name<input name="last_name" required maxlength="50" autocomplete="family-name"></label></div></div>
<label>Middle name (optional)<input name="middle_name" maxlength="50"></label>
<label>Email<input type="email" name="email" required maxlength="254" autocomplete="email"></label>
<label>Philippine mobile number<input name="phone" placeholder="09171234567" required inputmode="tel" autocomplete="tel"></label>
<label>Birthdate (18 or older)<input type="date" name="birthdate" required max="{{ now('Asia/Manila')->subYears(18)->format('Y-m-d') }}"></label>
<label>Address<input name="address" required maxlength="250" autocomplete="street-address"></label>
<label>Password<input type="password" name="password" minlength="8" maxlength="72" required autocomplete="new-password"></label>
<label>Confirm password<input type="password" name="password_confirmation" minlength="8" maxlength="72" required autocomplete="new-password"></label>
<label>Verify using<select name="verification_method"><option value="email">Email code</option><option value="sms">SMS code</option></select></label>
<div id="signup-sms" hidden><button type="button" class="secondary" id="send-signup-sms">Send signup SMS</button><label>SMS code<input name="otp_code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="one-time-code"></label></div>
<label><input type="checkbox" name="terms_accepted" value="1" required> I accept the <a href="/terms" target="_blank" rel="noopener">Terms and Conditions</a>.</label>
<button type="submit">Create account</button><p><small>Pets are added separately after verification and login.</small></p>
</form></section>
<div><section class="card"><h2>Sign in</h2><form id="login"><label>Email<input name="email" type="email" required autocomplete="username"></label><label>Password<input name="password" type="password" required autocomplete="current-password"></label><label>Login code channel<select name="channel"><option value="">Use my verified channel</option><option value="email">Email</option><option value="sms">SMS</option></select></label><button>Sign in</button></form></section>
<section class="card" id="verify-card"><h2>Enter your verification code</h2><form id="verify"><label>Purpose<select name="context"><option value="registration">Verify email registration</option><option value="login">Complete sign in</option></select></label><label>Channel<select name="channel"><option value="email">Email</option><option value="sms">SMS</option></select></label><label>Email or mobile number<input name="identifier" required></label><label>6-digit code<input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required autocomplete="one-time-code"></label><button>Verify code</button> <button class="secondary" type="button" id="resend">Resend code</button></form><small>Codes expire in 5 minutes. Wait 60 seconds between sends.</small></section></div>
<section class="card full"><h2>Password setup or reset</h2><p class="muted">Use this for a forgotten password or an account created for you by the clinic.</p><form id="reset-request"><label>Account email<input name="email" type="email" required></label><button class="secondary">Send email reset code</button></form><form id="reset-confirm"><label>Email<input name="email" type="email" required></label><label>Reset code<input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required></label><div class="row"><label>New password<input name="password" type="password" minlength="8" maxlength="72" required autocomplete="new-password"></label><label>Confirm new password<input name="password_confirmation" type="password" minlength="8" maxlength="72" required autocomplete="new-password"></label></div><button>Save new password</button></form></section>
</div></main></body></html>
